### ISSUE TITLE
This saddens me...

### ISSUE THREAD

**Issue by rdehuyss** [LUMASERV/jobrunr#2] opened 2022-06-29 07:44 UTC
Hi @lumaserv team,

These forks are the ones that want me to stop maintaining JobRunr. Reason for it is that if people will use your fork, the issues will come to me (this has happened in the past). On top of that, these forks end up being unmaintained often endangering the users that will use your fork.

Your company, Lumaserv, tries to make (or makes) a living by creating excelling features to make your customers happy. I'm happy JobRunr can help you with that. However, the whole open-source ecosystem is in danger because of these kind of forks. I've put more than 2500 hours (that's more than 300 working days) into JobRunr yet some people like you take it for granted without contributing back. Personally, I don't see this as a contribution to the OSS world because of the fact that all the issues from this fork will end up in my github repo resulting in me having a burn-out. I hope you understand my point of view and the fact why this saddens me.

FYI - there is a bug in the restart feature on exception you added.

@JanHolger : as it stands, I would prefer you stopped your sponsorship.

**Comment by JanHolger** [comment] 2022-06-29 21:12
Hi @rdehuyss,

> These forks are the ones that want me to stop maintaining JobRunr. Reason for it is that if people will use your fork, the issues will come to me (this has happened in the past).

we are not interested at all in making you more work with this fork and we are really greatful for the great work you've put into JobRunr so far.

> On top of that, these forks end up being unmaintained often endangering the users that will use your fork.
Totally agree on that and I'll try to make it more clear, that this is to be used at own risk.

Unfortunately we can't work with it, when it's that unstable. And I agree that the root cause for the crash should be fixed aswell but I hope you agree that a worker that can randomly crash without any notice isn't a good idea. We needed a fix for this and I opened an issue that you rejected. That's totally fine as it's your decision what should be included in the library but the only other solution for us was to put the effort into starting this fork, even though this also cost me a day of work.

> I've put more than 2500 hours (that's more than 300 working days) into JobRunr yet some people like you take it for granted without contributing back.

The reason we didn't start any pull-request is that you rejected all the issues we and other people opened regarding the issues we tried to address in this fork. If you would be willing to accept PR's regarding these issues, I would be happy to contribute to the original project but it really didn't look like you were interested in that.

If you are speaking about financial aspects: The moment I started using your library I personally started sponsoring the project to give something back and you are the first person I ever sponsored. As a company we were also considering buying a pro license both for the features and to give something back for the value that JobRunr brings to us, but till this day we are still not sure if we'll stay with JobRunr or replace it, as it doesn't fully cover all of our needs (at least not yet, I've seen instant scheduling is already on the Roadmap for Pro though) so we didn't aquire a Pro license yet.

> Personally, I don't see this as a contribution to the OSS world because of the fact that all the issues from this fork will end up in my github repo resulting in me having a burn-out. I hope you understand my point of view and the fact why this saddens me.

I accepted your PR and I'll also add some more clarification to the Readme that the fork is to be used at own risk and totally unsupported. If you have any more requests regarding more clarification feel free to open a PR, an issue or send us a mail to info@lumaserv.com. As you chose a license that prohibits private forks, unfortunately we can't make it private without breaking the license either. I understand your situation and that's why I've enabled the issue feature (it seems to be disabled for forks by default) so people can open issues on this repo and don't spam you.

> FYI - there is a bug in the restart feature on exception you added.

Thanks for the info, I'll try to look into it again but we haven't run into any issues yet.

> @JanHolger : as it stands, I would prefer you stopped your sponsorship.

Even though it's not much I thought I'll also personally give something back and I never expected special support if that's the issue you have with it but if you want me to cancel the sponsorship I'll do that. If you also want us to remove the links to your funding and promoting of the Pro version, please just tell me and I'll remove those aswell.

I'm sorry if this fork made you any inconvenience as that was definitely not our intent and I wish you a great week.

**Closed as completed** 2022-07-08 17:50 UTC
